"""Generate static/dynamic region masks for RadarOcc K-Radar occupancy evaluation.

This tool intentionally does NOT read raw radar tensors (arrDREA).  It reuses the
processed annotations produced by ``tools/process_kradar.py``:

    <data_root>/<clip>/bbox/bbox{frame}.npy
    <data_root>/<clip>/bbox/bbox_token{frame}.npy
    <data_root>/<clip>/bbox/object_category{frame}.npy
    <data_root>/<clip>/pose/lidar_ego_pose{frame}.npy

The motion state of each tracked object is estimated from the trajectory of its
3D-box centre after transforming that centre into the common/world coordinate
system with the LiDAR ego pose.  A short local linear fit is used instead of a
single two-frame difference to reduce annotation jitter.

Output per frame:

    motion_region_gt/motion_region_gt{frame}.npy

The dense mask is aligned with the final RadarOcc occupancy grid and uses:

    0   = static evaluation region
    1   = moving-object region
    255 = ignore / uncertain / outside radar FoV

The whole current 3D box is marked as a motion *region*.  It is NOT filled as
occupied ground truth; occupancy still comes from semantic_occupancy_gt_fov.
This keeps motion annotation and occupancy annotation separate.

A per-object CSV and per-frame NPZ metadata are also written to ``motion_meta``
for threshold inspection and debugging.

Typical usage from the repository root:

    python tools/generate_motion_region_gt.py \
        --data-root /mnt/data/DataSet/K-RadarOOC/train \
        --config tools/config.yaml \
        --clips 11 \
        --frame-period 0.1

IMPORTANT: ``--frame-period`` must match the temporal spacing of the processed
bbox/pose sequence.  The script deliberately requires it instead of silently
assuming a K-Radar frame rate.
"""

from __future__ import annotations

import argparse
import csv
import os
import re
from collections import defaultdict
from dataclasses import dataclass
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
import torch
import yaml
from mmcv.ops.points_in_boxes import points_in_boxes_cpu
from tqdm import tqdm


STATIC = np.uint8(0)
MOVING = np.uint8(1)
IGNORE = np.uint8(255)

STATE_NAME = {
    int(STATIC): "static",
    int(MOVING): "moving",
    int(IGNORE): "uncertain",
}


@dataclass
class TrackObservation:
    frame: int
    center_world: np.ndarray  # (3,)


@dataclass
class MotionEstimate:
    state: np.uint8
    speed: float
    vx: float
    vy: float
    n_obs: int
    fit_rmse: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate static/dynamic region GT from K-Radar tracking annotations."
    )
    parser.add_argument(
        "--data-root",
        type=str,
        default="/mnt/data/DataSet/K-RadarOOC/train",
        help=(
            "Root that contains processed clip folders. Each clip must contain "
            "bbox/ and pose/ generated by tools/process_kradar.py."
        ),
    )
    parser.add_argument(
        "--config",
        type=str,
        default="tools/config.yaml",
        help="RadarOcc GT-generation config. Used for voxel size and base pc_range.",
    )
    parser.add_argument(
        "--clips",
        nargs="*",
        default=None,
        help="Clip IDs to process, e.g. --clips 3 11 15. Omit to process all numeric clips.",
    )
    parser.add_argument(
        "--frame-period",
        type=float,
        required=True,
        help=(
            "Time in seconds between consecutive processed bbox/pose frames. "
            "Required because process_kradar.py does not preserve timestamps."
        ),
    )
    parser.add_argument(
        "--window",
        type=int,
        default=5,
        help="Odd local track window used for velocity fitting. Default: 5 frames.",
    )
    parser.add_argument(
        "--min-track-observations",
        type=int,
        default=3,
        help="Minimum observations in the local window; otherwise mark object uncertain.",
    )
    parser.add_argument(
        "--static-speed",
        type=float,
        default=0.2,
        help="Speed <= this value [m/s] is labelled static. Initial audit threshold.",
    )
    parser.add_argument(
        "--dynamic-speed",
        type=float,
        default=0.5,
        help="Speed >= this value [m/s] is labelled moving. Initial audit threshold.",
    )
    parser.add_argument(
        "--max-fit-rmse",
        type=float,
        default=0.5,
        help=(
            "Maximum XY trajectory-fit RMSE [m]. Larger residuals are marked uncertain. "
            "Set a negative value to disable this check."
        ),
    )
    parser.add_argument(
        "--z-crop-bins",
        type=int,
        default=6,
        help=(
            "Number of lower z bins removed by filter_kradar_fov.py. Default 6 converts "
            "the tools/config.yaml grid 128x128x20 to the model grid 128x128x14."
        ),
    )
    parser.add_argument(
        "--radar-azimuth-deg",
        type=float,
        default=53.5,
        help="Half horizontal Radar FoV angle used by filter_kradar_fov.py.",
    )
    parser.add_argument(
        "--radar-translation",
        type=float,
        nargs=3,
        default=(-2.54, 0.3, 0.7),
        metavar=("TX", "TY", "TZ"),
        help=(
            "LiDAR-to-radar translation convention used by current GT code. "
            "Default matches filter_kradar_fov.py."
        ),
    )
    parser.add_argument(
        "--output-dirname",
        type=str,
        default="motion_region_gt",
        help="Per-clip directory name for dense motion masks.",
    )
    parser.add_argument(
        "--meta-dirname",
        type=str,
        default="motion_meta",
        help="Per-clip directory name for motion metadata and CSV audit information.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing per-frame masks and metadata.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Compute labels and print summaries without writing files.",
    )
    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    if args.frame_period <= 0:
        raise ValueError("--frame-period must be > 0.")
    if args.window < 3 or args.window % 2 == 0:
        raise ValueError("--window must be an odd integer >= 3.")
    if args.min_track_observations < 2:
        raise ValueError("--min-track-observations must be >= 2.")
    if args.static_speed < 0 or args.dynamic_speed < 0:
        raise ValueError("Speed thresholds must be non-negative.")
    if args.static_speed >= args.dynamic_speed:
        raise ValueError("--static-speed must be smaller than --dynamic-speed.")


def discover_frame_indices(bbox_dir: str) -> List[int]:
    """Return frame IDs from bbox{N}.npy only (not bbox_token{N}.npy)."""
    pattern = re.compile(r"^bbox(\d+)\.npy$")
    indices: List[int] = []
    for name in os.listdir(bbox_dir):
        match = pattern.match(name)
        if match:
            indices.append(int(match.group(1)))
    return sorted(indices)


def load_pose(pose_dir: str, frame: int) -> np.ndarray:
    path = os.path.join(pose_dir, f"lidar_ego_pose{frame}.npy")
    pose = np.load(path, allow_pickle=True)
    pose = np.asarray(pose, dtype=np.float64)
    if pose.shape != (4, 4):
        raise ValueError(f"Expected 4x4 pose at {path}, got {pose.shape}.")
    return pose


def load_frame_annotations(
    bbox_dir: str, frame: int
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    boxes = np.load(os.path.join(bbox_dir, f"bbox{frame}.npy"), allow_pickle=True)
    tokens = np.load(
        os.path.join(bbox_dir, f"bbox_token{frame}.npy"), allow_pickle=True
    )
    category_path = os.path.join(bbox_dir, f"object_category{frame}.npy")
    if os.path.exists(category_path):
        categories = np.load(category_path, allow_pickle=True)
    else:
        categories = np.full((len(boxes),), -1, dtype=np.int64)

    boxes = np.asarray(boxes, dtype=np.float64).reshape(-1, 7)
    tokens = np.asarray(tokens).reshape(-1).astype(str)
    categories = np.asarray(categories).reshape(-1).astype(np.int64)

    if len(boxes) != len(tokens):
        raise ValueError(
            f"Frame {frame}: {len(boxes)} boxes but {len(tokens)} tracking tokens."
        )
    if len(categories) != len(boxes):
        raise ValueError(
            f"Frame {frame}: {len(boxes)} boxes but {len(categories)} categories."
        )
    return boxes, tokens, categories


def centres_to_common_coordinate(boxes: np.ndarray, pose: np.ndarray) -> np.ndarray:
    """Transform LiDAR-frame box centres into the pose/common coordinate system."""
    if len(boxes) == 0:
        return np.empty((0, 3), dtype=np.float64)
    centres_h = np.concatenate(
        [boxes[:, :3], np.ones((len(boxes), 1), dtype=np.float64)], axis=1
    )
    centres_world = (pose @ centres_h.T).T[:, :3]
    return centres_world


def build_tracks(
    bbox_dir: str, pose_dir: str, frame_indices: Sequence[int]
) -> Tuple[
    Dict[str, List[TrackObservation]],
    Dict[int, Tuple[np.ndarray, np.ndarray, np.ndarray]],
]:
    tracks: Dict[str, List[TrackObservation]] = defaultdict(list)
    frame_data: Dict[int, Tuple[np.ndarray, np.ndarray, np.ndarray]] = {}

    for frame in tqdm(frame_indices, desc="Reading bbox / pose", leave=False):
        boxes, tokens, categories = load_frame_annotations(bbox_dir, frame)
        pose = load_pose(pose_dir, frame)
        centres_world = centres_to_common_coordinate(boxes, pose)
        frame_data[frame] = (boxes, tokens, categories)

        for token, centre in zip(tokens, centres_world):
            tracks[str(token)].append(
                TrackObservation(frame=frame, center_world=centre.copy())
            )

    for token in tracks:
        tracks[token].sort(key=lambda obs: obs.frame)
    return tracks, frame_data


def fit_motion_for_observation(
    observations: Sequence[TrackObservation],
    query_frame: int,
    window: int,
    frame_period: float,
    min_observations: int,
    static_speed: float,
    dynamic_speed: float,
    max_fit_rmse: float,
) -> MotionEstimate:
    radius = window // 2
    local = [obs for obs in observations if abs(obs.frame - query_frame) <= radius]

    if len(local) < min_observations:
        return MotionEstimate(
            state=IGNORE,
            speed=np.nan,
            vx=np.nan,
            vy=np.nan,
            n_obs=len(local),
            fit_rmse=np.nan,
        )

    # Actual processed frame indices are used as time coordinates so missing
    # observations inside the local window do not silently compress time.
    t = np.asarray([obs.frame for obs in local], dtype=np.float64) * frame_period
    xy = np.asarray([obs.center_world[:2] for obs in local], dtype=np.float64)

    # Improve numerical conditioning without changing fitted slopes.
    t0 = t.mean()
    tc = t - t0
    design = np.stack([tc, np.ones_like(tc)], axis=1)

    coef_x, _, _, _ = np.linalg.lstsq(design, xy[:, 0], rcond=None)
    coef_y, _, _, _ = np.linalg.lstsq(design, xy[:, 1], rcond=None)
    vx = float(coef_x[0])
    vy = float(coef_y[0])
    speed = float(np.hypot(vx, vy))

    pred_x = design @ coef_x
    pred_y = design @ coef_y
    residual = np.stack([xy[:, 0] - pred_x, xy[:, 1] - pred_y], axis=1)
    fit_rmse = float(np.sqrt(np.mean(np.sum(residual * residual, axis=1))))

    if max_fit_rmse >= 0 and fit_rmse > max_fit_rmse:
        state = IGNORE
    elif speed <= static_speed:
        state = STATIC
    elif speed >= dynamic_speed:
        state = MOVING
    else:
        # Deliberate grey zone between static and moving thresholds.
        state = IGNORE

    return MotionEstimate(
        state=state,
        speed=speed,
        vx=vx,
        vy=vy,
        n_obs=len(local),
        fit_rmse=fit_rmse,
    )


def estimate_all_motion(
    tracks: Dict[str, List[TrackObservation]],
    window: int,
    frame_period: float,
    min_observations: int,
    static_speed: float,
    dynamic_speed: float,
    max_fit_rmse: float,
) -> Dict[Tuple[int, str], MotionEstimate]:
    estimates: Dict[Tuple[int, str], MotionEstimate] = {}
    for token, observations in tracks.items():
        for obs in observations:
            estimates[(obs.frame, token)] = fit_motion_for_observation(
                observations=observations,
                query_frame=obs.frame,
                window=window,
                frame_period=frame_period,
                min_observations=min_observations,
                static_speed=static_speed,
                dynamic_speed=dynamic_speed,
                max_fit_rmse=max_fit_rmse,
            )
    return estimates


def build_final_grid(
    config: dict, z_crop_bins: int
) -> Tuple[np.ndarray, np.ndarray, float, np.ndarray]:
    voxel_size = float(config["voxel_size"])
    base_pc_range = np.asarray(config["pc_range"], dtype=np.float64)
    base_occ_size = np.asarray(config["occ_size"], dtype=np.int64)

    if base_occ_size.shape != (3,) or base_pc_range.shape != (6,):
        raise ValueError("Expected occ_size[3] and pc_range[6] in config.")
    if z_crop_bins < 0 or z_crop_bins >= base_occ_size[2]:
        raise ValueError("Invalid --z-crop-bins for configured occ_size.")

    final_occ_size = base_occ_size.copy()
    final_occ_size[2] -= z_crop_bins

    final_pc_range = base_pc_range.copy()
    final_pc_range[2] += z_crop_bins * voxel_size

    expected = np.rint(
        (final_pc_range[3:] - final_pc_range[:3]) / voxel_size
    ).astype(np.int64)
    if not np.array_equal(expected, final_occ_size):
        raise ValueError(
            "Final pc_range / voxel_size is inconsistent with final occ_size: "
            f"expected {expected.tolist()}, got {final_occ_size.tolist()}."
        )

    xs = final_pc_range[0] + (np.arange(final_occ_size[0]) + 0.5) * voxel_size
    ys = final_pc_range[1] + (np.arange(final_occ_size[1]) + 0.5) * voxel_size
    zs = final_pc_range[2] + (np.arange(final_occ_size[2]) + 0.5) * voxel_size
    x, y, z = np.meshgrid(xs, ys, zs, indexing="ij")
    centres = np.stack([x, y, z], axis=-1).reshape(-1, 3)

    return final_pc_range, final_occ_size, voxel_size, centres


def build_radar_fov_mask(
    centres_lidar: np.ndarray,
    radar_translation: Sequence[float],
    half_azimuth_deg: float,
) -> np.ndarray:
    """Match the azimuth convention used by tools/filter_kradar_fov.py."""
    radar_translation = np.asarray(radar_translation, dtype=np.float64).reshape(1, 3)
    centres_radar = centres_lidar + radar_translation
    azimuth_deg = np.degrees(
        np.arctan2(centres_radar[:, 1], centres_radar[:, 0])
    )
    return np.abs(azimuth_deg) < half_azimuth_deg


def rasterize_motion_regions(
    boxes: np.ndarray,
    object_states: np.ndarray,
    valid_centres: np.ndarray,
    valid_flat_indices: np.ndarray,
    total_num_voxels: int,
    grid_size: np.ndarray,
) -> np.ndarray:
    """Rasterize current-frame oriented boxes with the same MMCV op as process_kradar."""
    flat = np.full((total_num_voxels,), IGNORE, dtype=np.uint8)
    region_valid = np.full((len(valid_centres),), STATIC, dtype=np.uint8)

    if len(boxes) > 0 and len(valid_centres) > 0:
        points_t = torch.from_numpy(valid_centres.astype(np.float32))[None, ...]
        boxes_t = torch.from_numpy(boxes.astype(np.float32))[None, ...]
        # Current process_kradar.py uses this exact operator/convention.
        inside = points_in_boxes_cpu(points_t, boxes_t)[0].cpu().numpy().astype(bool)

        moving_box_ids = np.flatnonzero(object_states == MOVING)
        uncertain_box_ids = np.flatnonzero(object_states == IGNORE)

        if len(moving_box_ids) > 0:
            moving_inside = np.any(inside[:, moving_box_ids], axis=1)
            region_valid[moving_inside] = MOVING

        if len(uncertain_box_ids) > 0:
            # Conservative choice: uncertainty wins in overlapping annotated boxes.
            uncertain_inside = np.any(inside[:, uncertain_box_ids], axis=1)
            region_valid[uncertain_inside] = IGNORE

    flat[valid_flat_indices] = region_valid
    return flat.reshape(tuple(int(v) for v in grid_size))


def write_frame_meta(
    path: str,
    boxes: np.ndarray,
    tokens: np.ndarray,
    categories: np.ndarray,
    frame: int,
    estimates: Dict[Tuple[int, str], MotionEstimate],
) -> None:
    states = []
    speeds = []
    vxs = []
    vys = []
    n_obs = []
    rmses = []
    for token in tokens:
        estimate = estimates[(frame, str(token))]
        states.append(int(estimate.state))
        speeds.append(estimate.speed)
        vxs.append(estimate.vx)
        vys.append(estimate.vy)
        n_obs.append(estimate.n_obs)
        rmses.append(estimate.fit_rmse)

    np.savez_compressed(
        path,
        frame=np.int64(frame),
        token=np.asarray(tokens).astype(str),
        category=np.asarray(categories, dtype=np.int64),
        bbox=np.asarray(boxes, dtype=np.float32),
        motion_state=np.asarray(states, dtype=np.uint8),
        speed_mps=np.asarray(speeds, dtype=np.float32),
        vx_mps=np.asarray(vxs, dtype=np.float32),
        vy_mps=np.asarray(vys, dtype=np.float32),
        n_fit_observations=np.asarray(n_obs, dtype=np.int16),
        fit_rmse_m=np.asarray(rmses, dtype=np.float32),
    )


def write_track_csv(
    path: str,
    clip: str,
    frame_data: Dict[int, Tuple[np.ndarray, np.ndarray, np.ndarray]],
    estimates: Dict[Tuple[int, str], MotionEstimate],
) -> None:
    with open(path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(
            [
                "clip",
                "frame",
                "tracking_id",
                "category",
                "state",
                "speed_mps",
                "vx_mps",
                "vy_mps",
                "n_fit_observations",
                "fit_rmse_m",
            ]
        )
        for frame in sorted(frame_data):
            _, tokens, categories = frame_data[frame]
            for token, category in zip(tokens, categories):
                estimate = estimates[(frame, str(token))]
                writer.writerow(
                    [
                        clip,
                        frame,
                        str(token),
                        int(category),
                        STATE_NAME[int(estimate.state)],
                        estimate.speed,
                        estimate.vx,
                        estimate.vy,
                        estimate.n_obs,
                        estimate.fit_rmse,
                    ]
                )


def process_clip(
    clip: str,
    args: argparse.Namespace,
    config: dict,
    final_occ_size: np.ndarray,
    all_centres: np.ndarray,
    valid_flat_mask: np.ndarray,
) -> None:
    clip_root = os.path.join(args.data_root, clip)
    bbox_dir = os.path.join(clip_root, "bbox")
    pose_dir = os.path.join(clip_root, "pose")

    if not os.path.isdir(bbox_dir):
        raise FileNotFoundError(f"Missing bbox directory: {bbox_dir}")
    if not os.path.isdir(pose_dir):
        raise FileNotFoundError(f"Missing pose directory: {pose_dir}")

    frame_indices = discover_frame_indices(bbox_dir)
    if not frame_indices:
        raise RuntimeError(f"No bbox{{frame}}.npy files found in {bbox_dir}")

    print(f"\n=== clip {clip}: {len(frame_indices)} frames ===")
    tracks, frame_data = build_tracks(bbox_dir, pose_dir, frame_indices)
    estimates = estimate_all_motion(
        tracks=tracks,
        window=args.window,
        frame_period=args.frame_period,
        min_observations=args.min_track_observations,
        static_speed=args.static_speed,
        dynamic_speed=args.dynamic_speed,
        max_fit_rmse=args.max_fit_rmse,
    )

    output_dir = os.path.join(clip_root, args.output_dirname)
    meta_dir = os.path.join(clip_root, args.meta_dirname)
    if not args.dry_run:
        os.makedirs(output_dir, exist_ok=True)
        os.makedirs(meta_dir, exist_ok=True)

    valid_flat_indices = np.flatnonzero(valid_flat_mask)
    valid_centres = all_centres[valid_flat_mask]
    total_num_voxels = int(np.prod(final_occ_size))

    object_state_counts = {"static": 0, "moving": 0, "uncertain": 0}
    moving_voxel_total = 0
    uncertain_voxel_total = 0

    for frame in tqdm(frame_indices, desc=f"Generating motion GT {clip}"):
        boxes, tokens, categories = frame_data[frame]
        object_states = np.asarray(
            [int(estimates[(frame, str(token))].state) for token in tokens],
            dtype=np.uint8,
        )

        for state in object_states:
            object_state_counts[STATE_NAME[int(state)]] += 1

        region_gt = rasterize_motion_regions(
            boxes=boxes,
            object_states=object_states,
            valid_centres=valid_centres,
            valid_flat_indices=valid_flat_indices,
            total_num_voxels=total_num_voxels,
            grid_size=final_occ_size,
        )

        moving_voxel_total += int(np.sum(region_gt == MOVING))
        uncertain_voxel_total += int(np.sum(region_gt == IGNORE))

        mask_path = os.path.join(output_dir, f"motion_region_gt{frame}.npy")
        meta_path = os.path.join(meta_dir, f"motion_info{frame}.npz")

        if not args.dry_run:
            if args.overwrite or not os.path.exists(mask_path):
                np.save(mask_path, region_gt)
            if args.overwrite or not os.path.exists(meta_path):
                write_frame_meta(
                    meta_path,
                    boxes=boxes,
                    tokens=tokens,
                    categories=categories,
                    frame=frame,
                    estimates=estimates,
                )

    if not args.dry_run:
        csv_path = os.path.join(meta_dir, "motion_tracks.csv")
        if args.overwrite or not os.path.exists(csv_path):
            write_track_csv(csv_path, clip, frame_data, estimates)

    print(
        "Object labels: "
        f"static={object_state_counts['static']}, "
        f"moving={object_state_counts['moving']}, "
        f"uncertain={object_state_counts['uncertain']}"
    )
    print(
        f"Voxel totals over frames: moving={moving_voxel_total}, "
        f"ignore/outside-FoV={uncertain_voxel_total}"
    )
    if not args.dry_run:
        print(f"Masks: {output_dir}")
        print(f"Audit metadata: {meta_dir}")


def main() -> None:
    args = parse_args()
    validate_args(args)

    with open(args.config, "r") as f:
        config = yaml.safe_load(f)

    final_pc_range, final_occ_size, voxel_size, centres = build_final_grid(
        config, args.z_crop_bins
    )
    valid_flat_mask = build_radar_fov_mask(
        centres_lidar=centres,
        radar_translation=args.radar_translation,
        half_azimuth_deg=args.radar_azimuth_deg,
    )

    print("Motion GT generation configuration")
    print(f"  data root          : {args.data_root}")
    print(f"  frame period [s]   : {args.frame_period}")
    print(f"  fit window         : {args.window}")
    print(f"  static <= [m/s]    : {args.static_speed}")
    print(f"  moving >= [m/s]    : {args.dynamic_speed}")
    print(f"  max fit RMSE [m]   : {args.max_fit_rmse}")
    print(f"  voxel size [m]     : {voxel_size}")
    print(f"  final pc range     : {final_pc_range.tolist()}")
    print(f"  final grid size    : {final_occ_size.tolist()}")
    print(f"  valid FoV voxels   : {int(valid_flat_mask.sum())}/{len(valid_flat_mask)}")
    print(
        "NOTE: speed thresholds are initial audit values. Inspect "
        "motion_meta/motion_tracks.csv before treating them as final labels."
    )

    if args.clips is None or len(args.clips) == 0:
        clips = sorted(
            name
            for name in os.listdir(args.data_root)
            if name.isnumeric() and os.path.isdir(os.path.join(args.data_root, name))
        )
    else:
        clips = [str(clip) for clip in args.clips]

    if not clips:
        raise RuntimeError(f"No numeric clip directories found under {args.data_root}")

    for clip in clips:
        process_clip(
            clip=clip,
            args=args,
            config=config,
            final_occ_size=final_occ_size,
            all_centres=centres,
            valid_flat_mask=valid_flat_mask,
        )


if __name__ == "__main__":
    main()
