"""Generate static / moving region masks for RadarOcc K-Radar evaluation.

This script intentionally does NOT read raw radar tensors. It reuses the
processed annotations already generated by tools/process_kradar.py:

    <data_root>/<clip>/bbox/bbox{frame}.npy
    <data_root>/<clip>/bbox/bbox_token{frame}.npy
    <data_root>/<clip>/bbox/object_category{frame}.npy
    <data_root>/<clip>/pose/lidar_ego_pose{frame}.npy

Motion state is estimated from each tracked 3D-box centre after transforming the
centre from the current LiDAR / ego frame into the common coordinate system with
the saved ego pose. A short local linear fit is used to reduce annotation jitter.

Output per frame:

    motion_region_gt/motion_region_gt{frame}.npy

Mask values:

    0   = static evaluation region
    1   = moving-object region
    255 = ignore / uncertain / outside radar FoV

The whole current 3D box is marked as a motion REGION. It is not converted into
occupied GT. Occupancy remains defined by semantic_occupancy_gt_fov.

Example:

    python tools/generate_motion_region_gt.py \
        --data-root /mnt/data/DataSet/K-RadarOOC/train \
        --config tools/config.yaml \
        --clips 11 \
        --frame-period 0.1

IMPORTANT: --frame-period must match the temporal spacing of the processed
bbox/pose sequence. The script does not silently assume a K-Radar frame rate.
"""

from __future__ import annotations

import argparse
import csv
import os
import re
from collections import defaultdict
from dataclasses import dataclass
from typing import Dict, List, Sequence, Tuple

import numpy as np
import torch
import yaml
from mmcv.ops.points_in_boxes import points_in_boxes_cpu
from tqdm import tqdm


STATIC = np.uint8(0)
MOVING = np.uint8(1)
IGNORE = np.uint8(255)

STATE_NAME = {
    int(STATIC): "static",
    int(MOVING): "moving",
    int(IGNORE): "uncertain",
}


@dataclass
class TrackObservation:
    frame: int
    center_world: np.ndarray


@dataclass
class MotionEstimate:
    state: np.uint8
    speed: float
    vx: float
    vy: float
    n_obs: int
    fit_rmse: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate K-Radar static/moving region GT from tracking annotations."
    )
    parser.add_argument(
        "--data-root",
        type=str,
        default="/mnt/data/DataSet/K-RadarOOC/train",
        help="Root containing processed numeric clip folders.",
    )
    parser.add_argument(
        "--config",
        type=str,
        default="tools/config.yaml",
        help="RadarOcc GT config used for voxel_size, pc_range and occ_size.",
    )
    parser.add_argument(
        "--clips",
        nargs="*",
        default=None,
        help="Clip IDs, e.g. --clips 3 11 15. Omit to process all numeric clips.",
    )
    parser.add_argument(
        "--frame-period",
        type=float,
        required=True,
        help="Seconds between consecutive processed bbox/pose frames.",
    )
    parser.add_argument(
        "--window",
        type=int,
        default=5,
        help="Odd local trajectory window used for velocity fitting. Default: 5.",
    )
    parser.add_argument(
        "--min-track-observations",
        type=int,
        default=3,
        help="Minimum observations required in the local fit. Default: 3.",
    )
    parser.add_argument(
        "--static-speed",
        type=float,
        default=0.2,
        help="Speed <= threshold [m/s] is labelled static. Initial audit value.",
    )
    parser.add_argument(
        "--dynamic-speed",
        type=float,
        default=0.5,
        help="Speed >= threshold [m/s] is labelled moving. Initial audit value.",
    )
    parser.add_argument(
        "--max-fit-rmse",
        type=float,
        default=0.5,
        help="Maximum XY fit RMSE [m]; larger values become uncertain. <0 disables.",
    )
    parser.add_argument(
        "--z-crop-bins",
        type=int,
        default=6,
        help="Lower z bins removed by filter_kradar_fov.py. Default: 6.",
    )
    parser.add_argument(
        "--radar-azimuth-deg",
        type=float,
        default=53.5,
        help="Radar horizontal half-FoV used by filter_kradar_fov.py.",
    )
    parser.add_argument(
        "--radar-translation",
        type=float,
        nargs=3,
        default=(-2.54, 0.3, 0.7),
        metavar=("TX", "TY", "TZ"),
        help="LiDAR-to-radar translation convention used by current GT code.",
    )
    parser.add_argument(
        "--output-dirname",
        type=str,
        default="motion_region_gt",
    )
    parser.add_argument(
        "--meta-dirname",
        type=str,
        default="motion_meta",
    )
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    if args.frame_period <= 0:
        raise ValueError("--frame-period must be > 0")
    if args.window < 3 or args.window % 2 == 0:
        raise ValueError("--window must be an odd integer >= 3")
    if args.min_track_observations < 2:
        raise ValueError("--min-track-observations must be >= 2")
    if args.static_speed < 0 or args.dynamic_speed < 0:
        raise ValueError("Speed thresholds must be non-negative")
    if args.static_speed >= args.dynamic_speed:
        raise ValueError("--static-speed must be smaller than --dynamic-speed")


def discover_frame_indices(bbox_dir: str) -> List[int]:
    pattern = re.compile(r"^bbox(\d+)\.npy$")
    frames = []
    for name in os.listdir(bbox_dir):
        match = pattern.match(name)
        if match:
            frames.append(int(match.group(1)))
    return sorted(frames)


def load_pose(pose_dir: str, frame: int) -> np.ndarray:
    path = os.path.join(pose_dir, f"lidar_ego_pose{frame}.npy")
    pose = np.asarray(np.load(path, allow_pickle=True), dtype=np.float64)
    if pose.shape != (4, 4):
        raise ValueError(f"Expected 4x4 pose at {path}, got {pose.shape}")
    return pose


def load_frame_annotations(
    bbox_dir: str, frame: int
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    boxes = np.asarray(
        np.load(os.path.join(bbox_dir, f"bbox{frame}.npy"), allow_pickle=True),
        dtype=np.float64,
    ).reshape(-1, 7)
    tokens = np.asarray(
        np.load(os.path.join(bbox_dir, f"bbox_token{frame}.npy"), allow_pickle=True)
    ).reshape(-1).astype(str)

    category_path = os.path.join(bbox_dir, f"object_category{frame}.npy")
    if os.path.exists(category_path):
        categories = np.asarray(
            np.load(category_path, allow_pickle=True)
        ).reshape(-1).astype(np.int64)
    else:
        categories = np.full((len(boxes),), -1, dtype=np.int64)

    if len(boxes) != len(tokens):
        raise ValueError(
            f"Frame {frame}: {len(boxes)} boxes but {len(tokens)} tracking IDs"
        )
    if len(categories) != len(boxes):
        raise ValueError(
            f"Frame {frame}: {len(boxes)} boxes but {len(categories)} categories"
        )
    return boxes, tokens, categories


def centers_to_world(boxes: np.ndarray, pose: np.ndarray) -> np.ndarray:
    if len(boxes) == 0:
        return np.empty((0, 3), dtype=np.float64)
    centers_h = np.concatenate(
        [boxes[:, :3], np.ones((len(boxes), 1), dtype=np.float64)], axis=1
    )
    return (pose @ centers_h.T).T[:, :3]


def build_tracks(
    bbox_dir: str,
    pose_dir: str,
    frame_indices: Sequence[int],
) -> Tuple[
    Dict[str, List[TrackObservation]],
    Dict[int, Tuple[np.ndarray, np.ndarray, np.ndarray]],
]:
    tracks: Dict[str, List[TrackObservation]] = defaultdict(list)
    frame_data = {}

    for frame in tqdm(frame_indices, desc="Read bbox/pose", leave=False):
        boxes, tokens, categories = load_frame_annotations(bbox_dir, frame)
        pose = load_pose(pose_dir, frame)
        centers_world = centers_to_world(boxes, pose)
        frame_data[frame] = (boxes, tokens, categories)

        for token, center in zip(tokens, centers_world):
            tracks[str(token)].append(
                TrackObservation(frame=frame, center_world=center.copy())
            )

    for token in tracks:
        tracks[token].sort(key=lambda item: item.frame)
    return tracks, frame_data


def fit_motion(
    observations: Sequence[TrackObservation],
    query_frame: int,
    window: int,
    frame_period: float,
    min_observations: int,
    static_speed: float,
    dynamic_speed: float,
    max_fit_rmse: float,
) -> MotionEstimate:
    radius = window // 2
    local = [
        obs for obs in observations
        if abs(obs.frame - query_frame) <= radius
    ]

    if len(local) < min_observations:
        return MotionEstimate(IGNORE, np.nan, np.nan, np.nan, len(local), np.nan)

    # Use original processed frame IDs as time coordinates so a missing
    # observation does not silently compress the time interval.
    time_s = np.asarray([obs.frame for obs in local], dtype=np.float64) * frame_period
    xy = np.asarray([obs.center_world[:2] for obs in local], dtype=np.float64)

    time_centered = time_s - time_s.mean()
    design = np.stack([time_centered, np.ones_like(time_centered)], axis=1)

    coef_x, _, _, _ = np.linalg.lstsq(design, xy[:, 0], rcond=None)
    coef_y, _, _, _ = np.linalg.lstsq(design, xy[:, 1], rcond=None)
    vx = float(coef_x[0])
    vy = float(coef_y[0])
    speed = float(np.hypot(vx, vy))

    pred = np.stack([design @ coef_x, design @ coef_y], axis=1)
    fit_rmse = float(np.sqrt(np.mean(np.sum((xy - pred) ** 2, axis=1))))

    if max_fit_rmse >= 0 and fit_rmse > max_fit_rmse:
        state = IGNORE
    elif speed <= static_speed:
        state = STATIC
    elif speed >= dynamic_speed:
        state = MOVING
    else:
        state = IGNORE

    return MotionEstimate(state, speed, vx, vy, len(local), fit_rmse)


def estimate_all_motion(
    tracks: Dict[str, List[TrackObservation]],
    args: argparse.Namespace,
) -> Dict[Tuple[int, str], MotionEstimate]:
    estimates = {}
    for token, observations in tracks.items():
        for obs in observations:
            estimates[(obs.frame, token)] = fit_motion(
                observations,
                obs.frame,
                args.window,
                args.frame_period,
                args.min_track_observations,
                args.static_speed,
                args.dynamic_speed,
                args.max_fit_rmse,
            )
    return estimates


def build_final_grid(config: dict, z_crop_bins: int):
    voxel_size = float(config["voxel_size"])
    base_pc_range = np.asarray(config["pc_range"], dtype=np.float64)
    base_occ_size = np.asarray(config["occ_size"], dtype=np.int64)

    if base_pc_range.shape != (6,) or base_occ_size.shape != (3,):
        raise ValueError("config must contain pc_range[6] and occ_size[3]")
    if z_crop_bins < 0 or z_crop_bins >= base_occ_size[2]:
        raise ValueError("Invalid --z-crop-bins")

    final_pc_range = base_pc_range.copy()
    final_pc_range[2] += z_crop_bins * voxel_size
    final_occ_size = base_occ_size.copy()
    final_occ_size[2] -= z_crop_bins

    expected = np.rint(
        (final_pc_range[3:] - final_pc_range[:3]) / voxel_size
    ).astype(np.int64)
    if not np.array_equal(expected, final_occ_size):
        raise ValueError(
            "Final pc_range / voxel_size does not match final occ_size: "
            f"expected {expected.tolist()}, got {final_occ_size.tolist()}"
        )

    xs = final_pc_range[0] + (np.arange(final_occ_size[0]) + 0.5) * voxel_size
    ys = final_pc_range[1] + (np.arange(final_occ_size[1]) + 0.5) * voxel_size
    zs = final_pc_range[2] + (np.arange(final_occ_size[2]) + 0.5) * voxel_size
    x, y, z = np.meshgrid(xs, ys, zs, indexing="ij")
    centers = np.stack([x, y, z], axis=-1).reshape(-1, 3)
    return centers, final_pc_range, final_occ_size, voxel_size


def make_radar_fov_mask(
    centers: np.ndarray,
    occ_size: np.ndarray,
    radar_translation: Sequence[float],
    azimuth_deg: float,
) -> np.ndarray:
    # Match filter_kradar_fov.py convention:
    # cart_voxels_radar = cart_voxels + [-2.54, 0.3, 0.7]
    radar_xyz = centers + np.asarray(radar_translation, dtype=np.float64)[None, :]
    azimuth = np.degrees(np.arctan2(radar_xyz[:, 1], radar_xyz[:, 0]))
    valid = np.abs(azimuth) < azimuth_deg
    return valid.reshape(tuple(occ_size.tolist()))


def boxes_to_dense_membership(
    grid_centers: np.ndarray,
    boxes: np.ndarray,
) -> np.ndarray:
    """Return [N_voxels, N_boxes] bool membership using current mmcv convention."""
    if len(boxes) == 0:
        return np.zeros((len(grid_centers), 0), dtype=bool)

    points = torch.from_numpy(grid_centers[None].astype(np.float32))
    boxes_t = torch.from_numpy(boxes[None].astype(np.float32))
    membership = points_in_boxes_cpu(points, boxes_t)[0].cpu().numpy().astype(bool)
    return membership


def generate_frame_mask(
    frame: int,
    boxes: np.ndarray,
    tokens: np.ndarray,
    grid_centers: np.ndarray,
    final_occ_size: np.ndarray,
    radar_fov_mask: np.ndarray,
    estimates: Dict[Tuple[int, str], MotionEstimate],
) -> Tuple[np.ndarray, List[MotionEstimate]]:
    mask = np.full(tuple(final_occ_size.tolist()), IGNORE, dtype=np.uint8)
    mask[radar_fov_mask] = STATIC

    frame_estimates = [estimates[(frame, str(token))] for token in tokens]
    if len(boxes) == 0:
        return mask, frame_estimates

    membership = boxes_to_dense_membership(grid_centers, boxes)
    flat = mask.reshape(-1)

    # First mark uncertain boxes as ignore; moving boxes are applied afterwards
    # and therefore take precedence in the unlikely event of box overlap.
    for box_idx, estimate in enumerate(frame_estimates):
        if estimate.state == IGNORE:
            flat[membership[:, box_idx]] = IGNORE

    for box_idx, estimate in enumerate(frame_estimates):
        if estimate.state == MOVING:
            flat[membership[:, box_idx]] = MOVING

    # Ensure voxels outside the Radar FoV always remain ignored.
    flat[~radar_fov_mask.reshape(-1)] = IGNORE
    return mask, frame_estimates


def write_clip_csv(
    path: str,
    frame_data: Dict[int, Tuple[np.ndarray, np.ndarray, np.ndarray]],
    estimates: Dict[Tuple[int, str], MotionEstimate],
) -> None:
    with open(path, "w", newline="") as file:
        writer = csv.writer(file)
        writer.writerow([
            "frame",
            "tracking_id",
            "category",
            "state",
            "speed_mps",
            "vx_mps",
            "vy_mps",
            "n_fit_observations",
            "fit_rmse_m",
        ])
        for frame in sorted(frame_data):
            _, tokens, categories = frame_data[frame]
            for token, category in zip(tokens, categories):
                estimate = estimates[(frame, str(token))]
                writer.writerow([
                    frame,
                    str(token),
                    int(category),
                    STATE_NAME[int(estimate.state)],
                    estimate.speed,
                    estimate.vx,
                    estimate.vy,
                    estimate.n_obs,
                    estimate.fit_rmse,
                ])


def process_clip(
    clip: str,
    args: argparse.Namespace,
    config: dict,
    grid_centers: np.ndarray,
    final_occ_size: np.ndarray,
    radar_fov_mask: np.ndarray,
) -> None:
    clip_root = os.path.join(args.data_root, clip)
    bbox_dir = os.path.join(clip_root, "bbox")
    pose_dir = os.path.join(clip_root, "pose")

    if not os.path.isdir(bbox_dir) or not os.path.isdir(pose_dir):
        print(f"[skip] clip {clip}: missing bbox/ or pose/")
        return

    frame_indices = discover_frame_indices(bbox_dir)
    if not frame_indices:
        print(f"[skip] clip {clip}: no bbox*.npy files")
        return

    missing_pose = [
        frame for frame in frame_indices
        if not os.path.exists(os.path.join(pose_dir, f"lidar_ego_pose{frame}.npy"))
    ]
    if missing_pose:
        raise FileNotFoundError(
            f"clip {clip}: missing poses for frames {missing_pose[:10]}"
        )

    print(f"\n=== clip {clip}: {len(frame_indices)} frames ===")
    tracks, frame_data = build_tracks(bbox_dir, pose_dir, frame_indices)
    estimates = estimate_all_motion(tracks, args)

    state_counts = {"static": 0, "moving": 0, "uncertain": 0}
    for estimate in estimates.values():
        state_counts[STATE_NAME[int(estimate.state)]] += 1
    print("object observations:", state_counts)

    output_dir = os.path.join(clip_root, args.output_dirname)
    meta_dir = os.path.join(clip_root, args.meta_dirname)
    if not args.dry_run:
        os.makedirs(output_dir, exist_ok=True)
        os.makedirs(meta_dir, exist_ok=True)
        write_clip_csv(os.path.join(meta_dir, "motion_tracks.csv"), frame_data, estimates)

    for frame in tqdm(frame_indices, desc=f"Generate clip {clip}"):
        boxes, tokens, categories = frame_data[frame]
        mask, frame_estimates = generate_frame_mask(
            frame,
            boxes,
            tokens,
            grid_centers,
            final_occ_size,
            radar_fov_mask,
            estimates,
        )

        if args.dry_run:
            continue

        mask_path = os.path.join(output_dir, f"motion_region_gt{frame}.npy")
        meta_path = os.path.join(meta_dir, f"motion_info{frame}.npz")
        if not args.overwrite and (os.path.exists(mask_path) or os.path.exists(meta_path)):
            continue

        np.save(mask_path, mask)
        np.savez_compressed(
            meta_path,
            tracking_id=tokens.astype(str),
            category=categories.astype(np.int64),
            motion_state=np.asarray([e.state for e in frame_estimates], dtype=np.uint8),
            speed_mps=np.asarray([e.speed for e in frame_estimates], dtype=np.float32),
            vx_mps=np.asarray([e.vx for e in frame_estimates], dtype=np.float32),
            vy_mps=np.asarray([e.vy for e in frame_estimates], dtype=np.float32),
            fit_rmse_m=np.asarray([e.fit_rmse for e in frame_estimates], dtype=np.float32),
            n_fit_observations=np.asarray([e.n_obs for e in frame_estimates], dtype=np.int16),
            bbox=boxes.astype(np.float32),
        )


def main() -> None:
    args = parse_args()
    validate_args(args)

    with open(args.config, "r") as file:
        config = yaml.safe_load(file)

    grid_centers, final_pc_range, final_occ_size, voxel_size = build_final_grid(
        config, args.z_crop_bins
    )
    radar_fov_mask = make_radar_fov_mask(
        grid_centers,
        final_occ_size,
        args.radar_translation,
        args.radar_azimuth_deg,
    )

    print("Final motion GT grid")
    print("  pc_range  :", final_pc_range.tolist())
    print("  occ_size  :", final_occ_size.tolist())
    print("  voxel_size:", voxel_size)
    print("  valid FoV :", int(radar_fov_mask.sum()), "/", radar_fov_mask.size)
    print("Motion thresholds")
    print(f"  static    : <= {args.static_speed:.3f} m/s")
    print(f"  uncertain : ({args.static_speed:.3f}, {args.dynamic_speed:.3f}) m/s")
    print(f"  moving    : >= {args.dynamic_speed:.3f} m/s")

    if args.clips is None:
        clips = sorted(
            name for name in os.listdir(args.data_root)
            if name.isnumeric() and os.path.isdir(os.path.join(args.data_root, name))
        )
    else:
        clips = [str(clip) for clip in args.clips]

    for clip in clips:
        process_clip(
            clip,
            args,
            config,
            grid_centers,
            final_occ_size,
            radar_fov_mask,
        )


if __name__ == "__main__":
    main()
