"""Visualize generated motion GT on K-Radar camera images as a GIF.

The visualization is intentionally an evaluation/debugging tool. It does not
change the generated motion GT. For each processed frame it shows:

    left  : raw front-camera image
    right : the same image with projected 3D boxes, tracking IDs, motion state,
            and estimated world-frame speed

Motion colors:
    green  = static (0)
    red    = moving (1)
    yellow = uncertain / ignore (255)

The script reads the per-frame metadata generated by
``tools/generate_motion_region_gt.py``:

    <data_root>/<seq>/motion_meta/motion_info{frame}.npz

Camera frames are matched by sorted order. ``--camera-offset`` can be used if
the first processed frame corresponds to a later camera image.

Example:

    python tools/visualize_motion_gt_camera_gif.py \
        --seq 4 \
        --data-root /home/user1/projects/RadarOcc/data/K-RadarOcc/train \
        --camera-dir /home/user1/projects/RadarOcc/data/K-Radar-RGB/K-Radar/K-Radar-RGB/4/images_rb_switched \
        --start-frame 0 --end-frame 200 --stride 2 --fps 5
"""

from __future__ import annotations

import argparse
import glob
import os
import re
from typing import Dict, Iterable, List, Sequence, Tuple

import cv2
import imageio.v2 as imageio
import numpy as np


STATIC = 0
MOVING = 1
IGNORE = 255

STATE_NAME = {
    STATIC: "STATIC",
    MOVING: "MOVING",
    IGNORE: "UNCERTAIN",
}

# BGR for OpenCV.
STATE_COLOR = {
    STATIC: (0, 210, 0),
    MOVING: (0, 0, 255),
    IGNORE: (0, 220, 255),
}

CATEGORY_NAME = {
    0: "Empty",
    1: "Static",
    2: "Sedan",
    3: "Bus/Truck",
    4: "Motorcycle",
    5: "Bicycle",
    6: "Pedestrian",
    7: "Pedestrian Group",
    8: "Bicycle Group",
    -1: "Unknown",
}

# Same LiDAR-to-front-camera projection matrix already used by
# tools/gen_data/gen_depth_gt_kradar.py in this repository.
PROJECTION = np.array(
    [
        [6.29238090e02, -5.27036820e02, -4.59938064e00, 1.41321630e03],
        [3.72013478e02, 9.42970300e00, -5.59685543e02, 1.07637845e03],
        [9.99925370e-01, 1.22165356e-02, 1.06612091e-04, 1.84000000e00],
    ],
    dtype=np.float64,
)

# 8-corner cuboid edge list.
BOX_EDGES = [
    (0, 1), (1, 2), (2, 3), (3, 0),
    (4, 5), (5, 6), (6, 7), (7, 4),
    (0, 4), (1, 5), (2, 6), (3, 7),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create raw-camera vs motion-GT overlay GIF for K-Radar."
    )
    parser.add_argument("--seq", type=int, default=4)
    parser.add_argument(
        "--data-root",
        type=str,
        default="/home/user1/projects/RadarOcc/data/K-RadarOcc/train",
    )
    parser.add_argument(
        "--camera-dir",
        type=str,
        required=True,
        help="Directory containing the corresponding camera images.",
    )
    parser.add_argument("--start-frame", type=int, default=0)
    parser.add_argument(
        "--end-frame",
        type=int,
        default=None,
        help="Inclusive processed-frame index. Default: last available motion frame.",
    )
    parser.add_argument("--stride", type=int, default=1)
    parser.add_argument("--fps", type=float, default=5.0)
    parser.add_argument(
        "--camera-offset",
        type=int,
        default=0,
        help="camera_index = processed_frame + camera_offset. Default: 0.",
    )
    parser.add_argument(
        "--panel-width",
        type=int,
        default=800,
        help="Width of each camera panel before concatenation.",
    )
    parser.add_argument(
        "--crop-width",
        type=int,
        default=1280,
        help="Crop camera to this width before projection; <=0 disables crop.",
    )
    parser.add_argument(
        "--line-thickness",
        type=int,
        default=2,
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="GIF path. Default: outputs/motion_gt_camera/seq<seq>_motion_validation.gif",
    )
    return parser.parse_args()


def natural_key(path: str):
    name = os.path.basename(path)
    return [int(x) if x.isdigit() else x.lower() for x in re.split(r"(\d+)", name)]


def discover_camera_images(camera_dir: str) -> List[str]:
    patterns = ["*.png", "*.jpg", "*.jpeg", "*.bmp"]
    paths: List[str] = []
    for pattern in patterns:
        paths.extend(glob.glob(os.path.join(camera_dir, pattern)))
    return sorted(set(paths), key=natural_key)


def discover_motion_frames(meta_dir: str) -> List[int]:
    pattern = re.compile(r"motion_info(\d+)\.npz$")
    frames = []
    for path in glob.glob(os.path.join(meta_dir, "motion_info*.npz")):
        match = pattern.search(os.path.basename(path))
        if match:
            frames.append(int(match.group(1)))
    return sorted(frames)


def box_corners_bottom_center(box: np.ndarray) -> np.ndarray:
    """Return 8 LiDAR-frame corners for [x,y,z,dx,dy,dz,yaw].

    The current RadarOcc preprocessing/MMCV convention uses z as the bottom
    centre. Therefore bottom corners have z and top corners have z + dz.
    """
    x, y, z, dx, dy, dz, yaw = [float(v) for v in box]

    local = np.array(
        [
            [ dx / 2,  dy / 2, 0.0],
            [ dx / 2, -dy / 2, 0.0],
            [-dx / 2, -dy / 2, 0.0],
            [-dx / 2,  dy / 2, 0.0],
            [ dx / 2,  dy / 2, dz],
            [ dx / 2, -dy / 2, dz],
            [-dx / 2, -dy / 2, dz],
            [-dx / 2,  dy / 2, dz],
        ],
        dtype=np.float64,
    )

    c = np.cos(yaw)
    s = np.sin(yaw)
    rotation = np.array(
        [[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]], dtype=np.float64
    )
    corners = local @ rotation.T
    corners += np.array([x, y, z], dtype=np.float64)
    return corners


def project_points(points_xyz: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    ones = np.ones((len(points_xyz), 1), dtype=np.float64)
    homogeneous = np.concatenate([points_xyz, ones], axis=1).T
    uvw = (PROJECTION @ homogeneous).T
    depth = uvw[:, 2]
    uv = np.full((len(points_xyz), 2), np.nan, dtype=np.float64)
    valid = depth > 1e-6
    uv[valid] = uvw[valid, :2] / depth[valid, None]
    return uv, depth


def draw_box(
    image: np.ndarray,
    box: np.ndarray,
    color: Tuple[int, int, int],
    label: str,
    thickness: int,
) -> bool:
    corners = box_corners_bottom_center(box)
    uv, depth = project_points(corners)

    # If no corner is in front of the camera, skip the box.
    if not np.any(depth > 0):
        return False

    h, w = image.shape[:2]
    drew_any = False
    for i, j in BOX_EDGES:
        if depth[i] <= 0 or depth[j] <= 0:
            continue
        p1 = tuple(np.rint(uv[i]).astype(int))
        p2 = tuple(np.rint(uv[j]).astype(int))

        # Ignore absurd projections caused by near-zero depth.
        if max(abs(p1[0]), abs(p1[1]), abs(p2[0]), abs(p2[1])) > 100000:
            continue

        cv2.line(image, p1, p2, color, thickness, cv2.LINE_AA)
        drew_any = True

    if not drew_any:
        return False

    positive = depth > 0
    visible_uv = uv[positive]
    if len(visible_uv):
        anchor_x = int(np.clip(np.nanmin(visible_uv[:, 0]), 0, max(0, w - 1)))
        anchor_y = int(np.clip(np.nanmin(visible_uv[:, 1]) - 6, 18, max(18, h - 1)))
        font = cv2.FONT_HERSHEY_SIMPLEX
        scale = 0.48
        text_thickness = 1
        (tw, th), baseline = cv2.getTextSize(label, font, scale, text_thickness)
        x1 = max(0, min(anchor_x, w - tw - 8))
        y1 = max(th + 6, anchor_y)
        cv2.rectangle(
            image,
            (x1 - 3, y1 - th - 5),
            (x1 + tw + 3, y1 + baseline + 3),
            (0, 0, 0),
            -1,
        )
        cv2.putText(
            image,
            label,
            (x1, y1),
            font,
            scale,
            color,
            text_thickness,
            cv2.LINE_AA,
        )
    return True


def resize_to_width(image: np.ndarray, width: int) -> np.ndarray:
    if width <= 0 or image.shape[1] == width:
        return image
    scale = width / float(image.shape[1])
    height = max(1, int(round(image.shape[0] * scale)))
    return cv2.resize(image, (width, height), interpolation=cv2.INTER_AREA)


def add_header(image: np.ndarray, title: str, subtitle: str) -> np.ndarray:
    header_h = 62
    canvas = cv2.copyMakeBorder(
        image, header_h, 0, 0, 0, cv2.BORDER_CONSTANT, value=(20, 20, 20)
    )
    cv2.putText(
        canvas,
        title,
        (12, 24),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.65,
        (255, 255, 255),
        2,
        cv2.LINE_AA,
    )
    cv2.putText(
        canvas,
        subtitle,
        (12, 49),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.48,
        (210, 210, 210),
        1,
        cv2.LINE_AA,
    )
    return canvas


def make_frame(
    image_path: str,
    meta_path: str,
    processed_frame: int,
    camera_index: int,
    panel_width: int,
    crop_width: int,
    line_thickness: int,
) -> np.ndarray:
    raw = cv2.imread(image_path, cv2.IMREAD_COLOR)
    if raw is None:
        raise RuntimeError(f"Failed to read image: {image_path}")

    if crop_width > 0 and raw.shape[1] > crop_width:
        raw = raw[:, :crop_width].copy()

    overlay = raw.copy()
    meta = np.load(meta_path, allow_pickle=True)

    tokens = np.asarray(meta["tracking_id"]).reshape(-1).astype(str)
    categories = np.asarray(meta["category"]).reshape(-1).astype(int)
    states = np.asarray(meta["motion_state"]).reshape(-1).astype(int)
    speeds = np.asarray(meta["speed_mps"]).reshape(-1).astype(float)
    rmses = np.asarray(meta["fit_rmse_m"]).reshape(-1).astype(float)
    boxes = np.asarray(meta["bbox"]).reshape(-1, 7).astype(float)

    counts: Dict[int, int] = {STATIC: 0, MOVING: 0, IGNORE: 0}
    projected = 0

    for token, category, state, speed, rmse, box in zip(
        tokens, categories, states, speeds, rmses, boxes
    ):
        state = int(state)
        counts[state] = counts.get(state, 0) + 1
        color = STATE_COLOR.get(state, STATE_COLOR[IGNORE])
        state_name = STATE_NAME.get(state, "UNKNOWN")
        category_name = CATEGORY_NAME.get(int(category), str(int(category)))
        speed_text = "nan" if not np.isfinite(speed) else f"{speed:.2f}m/s"
        rmse_text = "nan" if not np.isfinite(rmse) else f"R{rmse:.2f}"
        label = f"ID {token} {category_name} {state_name} {speed_text} {rmse_text}"
        if draw_box(overlay, box, color, label, line_thickness):
            projected += 1

    # Legend on the overlay image itself.
    legend_lines = [
        ("STATIC", STATE_COLOR[STATIC]),
        ("MOVING", STATE_COLOR[MOVING]),
        ("UNCERTAIN", STATE_COLOR[IGNORE]),
    ]
    y = 26
    for text, color in legend_lines:
        cv2.rectangle(overlay, (12, y - 13), (28, y + 3), color, -1)
        cv2.putText(
            overlay, text, (36, y), cv2.FONT_HERSHEY_SIMPLEX, 0.5,
            (255, 255, 255), 1, cv2.LINE_AA
        )
        y += 24

    overlay = resize_to_width(overlay, panel_width)

    image_name = os.path.basename(image_path)
    overlay = add_header(
        overlay,
        f"Motion GT | Seq {processed_frame}",
        (
            f"frame={processed_frame}  camera={camera_index}  "
            f"static={counts.get(STATIC,0)}  moving={counts.get(MOVING,0)}  "
            f"uncertain={counts.get(IGNORE,0)}  projected={projected}"
        ),
    )

    return cv2.cvtColor(overlay, cv2.COLOR_BGR2RGB)


def main() -> None:
    args = parse_args()
    if args.stride <= 0:
        raise ValueError("--stride must be > 0")
    if args.fps <= 0:
        raise ValueError("--fps must be > 0")

    seq_root = os.path.join(args.data_root, str(args.seq))
    meta_dir = os.path.join(seq_root, "motion_meta")
    if not os.path.isdir(meta_dir):
        raise FileNotFoundError(f"Missing motion_meta directory: {meta_dir}")
    if not os.path.isdir(args.camera_dir):
        raise FileNotFoundError(f"Missing camera directory: {args.camera_dir}")

    motion_frames = discover_motion_frames(meta_dir)
    if not motion_frames:
        raise RuntimeError(f"No motion_info*.npz found in {meta_dir}")

    camera_images = discover_camera_images(args.camera_dir)
    if not camera_images:
        raise RuntimeError(f"No camera images found in {args.camera_dir}")

    end_frame = args.end_frame if args.end_frame is not None else motion_frames[-1]
    selected_frames = [
        f for f in motion_frames
        if args.start_frame <= f <= end_frame and (f - args.start_frame) % args.stride == 0
    ]
    if not selected_frames:
        raise RuntimeError("No motion frames selected by the requested range/stride.")

    if args.output is None:
        output = os.path.join(
            "outputs", "motion_gt_camera", f"seq{args.seq}_motion_validation.gif"
        )
    else:
        output = args.output
    os.makedirs(os.path.dirname(os.path.abspath(output)), exist_ok=True)

    print(f"Sequence        : {args.seq}")
    print(f"Motion frames   : {len(motion_frames)} ({motion_frames[0]}..{motion_frames[-1]})")
    print(f"Camera images   : {len(camera_images)}")
    print(f"Selected frames : {len(selected_frames)}")
    print(f"Camera offset   : {args.camera_offset}")
    print(f"Output          : {output}")

    duration = 1.0 / args.fps
    written = 0
    with imageio.get_writer(output, mode="I", duration=duration, loop=0) as writer:
        for frame in selected_frames:
            camera_index = frame + args.camera_offset
            if camera_index < 0 or camera_index >= len(camera_images):
                print(
                    f"[skip] frame {frame}: camera index {camera_index} out of range "
                    f"[0, {len(camera_images)-1}]"
                )
                continue

            meta_path = os.path.join(meta_dir, f"motion_info{frame}.npz")
            rgb = make_frame(
                camera_images[camera_index],
                meta_path,
                frame,
                camera_index,
                args.panel_width,
                args.crop_width,
                args.line_thickness,
            )
            writer.append_data(rgb)
            written += 1
            if written % 25 == 0 or written == len(selected_frames):
                print(f"  wrote {written}/{len(selected_frames)} frames")

    if written == 0:
        raise RuntimeError("No GIF frames were written.")
    print(f"Done: {output}")


if __name__ == "__main__":
    main()
